### ISSUE TITLE
Disambiguation should consider moves including illegal ones

### ISSUE THREAD

**Issue by sugyan** [koba-e964/shogi_official_kifu#5]
In the following case, `display_single_move` should return `▲５６銀左` and `▲５６銀右`, but it returns `▲５６銀`.
Apparently, because `disambiguate` enumerates candidate moves from `LiteLegalityChecker.all_legal_moves_partial`, an illegal move `from SQ_6E to SQ_5F` will be excluded from candidates to consider ambiguity.

![65](https://user-images.githubusercontent.com/80381/182853583-7ac6df42-e049-49b6-a01c-c78adfbd352b.png)

```rust
    #[test]
    fn normal_includes_illegal() {
        // Examples found in https://www.shogi.or.jp/faq/kihuhyouki.html, with B_K on SQ_5E and W_R on SQ_7E
        let pos = PartialPosition::from_usi("sfen 4k4/G1G3G1G/9/9/2rSKS3/9/9/9/9 b - 1").unwrap();

        // C
        let mv = Move::Normal {
            from: Square::SQ_6E,
            to: Square::SQ_5F,
            promote: false,
        };
        let result = display_single_move(&pos, mv);
        assert_eq!(result, Some("▲５６銀左".to_string()));
        let mv = Move::Normal {
            from: Square::SQ_4E,
            to: Square::SQ_5F,
            promote: false,
        };
        let result = display_single_move(&pos, mv);
        assert_eq!(result, Some("▲５６銀右".to_string()));
    }
```

**Comment by koba-e964** [comment]
一応認識はしてはいましたが、公式のルール解説ページにそれについて明確に書かれた箇所が見つからなかったため + 実装が不可能ではないが面倒に思えたため放置していました。
まだそれがよいかどうか、100% の確信は持てていませんがおそらくよさそうだと思うので、暇を見つけて実装します
/
I was aware of this issue but haven't fixed it because:
- there are no description about this case in the official rule page
- to me the implementation seemed tedious, if not impossible

Not 100% sure it's the best way to go to fix this yet, but I'm going to fix this because it's probably better than the current situation.
